### ISSUE TITLE
is there a documentation?

### ISSUE THREAD

**Issue by chanansh** [ramedina86/streamsync#1]
No documentation is available. do you support pyplot figures? what other widgets do you support?

**Comment by ramedina86** [comment]
Hi, thanks for your interest in this repository. This was meant to be a quick POC to show a new that a faster alternative to Streamlit is possible. The goal of the project was just to propose and discuss a new architecture for data apps, which I did in the Medium article. At this stage, it's not meant to be an alternative to Streamlit.

Nevertheless, since there was enough interest in it, I'm developing this quick POC into fully-fledged software. As such, it'll include documentation and will be easily installable (PyPI package). This new version will be a direct competitor to Streamlit. I expect to release it in 2023 Q1.

**Comment by franciscoed** [comment]
@ramedina86 just found your medium page! Please let me know if you need any help with documentation, translation and other things.

**Comment by ramedina86** [comment]
Streamsync is now a fully featured framework, I just released the first version. It's pip-installable and the documentation is available at https://streamsync.cloud You can check the "Component list" section to get an idea of the components currently supported.

Thank you for your interest!
